name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish BlazorPWA.csproj -c Release -o release --nologo

      - name: Change base-tag to match GitHub subfolder
        run: sed -i 's/<base href="\/" \/>/<base href="\/lastdrop\/" \/>/g' release/wwwroot/index.html

      - name: Copy index to 404
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4